In [58]:
import pandas as pd

In [59]:
df = pd.read_csv("netflix_titles.csv")
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [60]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 3.9 MB

In [61]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [62]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [63]:
df = df.drop_duplicates()
df['director'] = df['director'].fillna("Unknown")

df['cast'] = df['cast'].fillna("Unknown")

df['country'] = df['country'].str.strip()
df['country'] = df['country'].fillna("Unknown")

df['date_added'] = df['date_added'].fillna(df['date_added'].mode()[0])
df['date_added'] = df['date_added'].str.strip()
df['date_added'] = pd.to_datetime(df['date_added'])

df['duration'] = df['duration'].fillna(df['duration'].mode()[0])

df['rating'] = df['rating'].fillna(df['rating'].mode()[0])

In [64]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [65]:
df.sample(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5182,s5183,Movie,Let It Fall: Los Angeles 1982-1992,John Ridley,Unknown,United States,2017-11-06,2017,TV-MA,144 min,Documentaries,This documentary chronicles simmering tension ...
175,s176,Movie,The Blue Lagoon,Randal Kleiser,"Brooke Shields, Christopher Atkins, Leo McKern...",United States,2021-09-01,1980,R,105 min,"Dramas, Romantic Movies","Two shipwrecked children, stranded for years o..."
7206,s7207,Movie,Kilo Two Bravo,Paul Katis,"David Elliot, Mark Stanley, Scott Kyle, Benjam...",United Kingdom,2019-03-01,2014,R,109 min,"Dramas, Independent Movies, Thrillers","On patrol in Afghanistan, a British paratroope..."
4570,s4571,TV Show,Hot Date,Unknown,"Emily Axford, Brian Murphy",United States,2018-10-01,2018,TV-MA,1 Season,"Romantic TV Shows, TV Comedies",Interconnected sketches and performances skewe...
4731,s4732,Movie,Raajneeti,Prakash Jha,"Ajay Devgn, Nana Patekar, Ranbir Kapoor, Katri...",India,2018-08-02,2010,TV-14,162 min,"Dramas, International Movies, Thrillers",When the American-educated scion of a powerful...
5313,s5314,Movie,The Lost Brother,Israel Adrián Caetano,"Leonardo Sbaraglia, Daniel Hendler, Ángela Mol...","Argentina, Uruguay, Spain, France",2017-09-01,2017,TV-MA,113 min,"Dramas, International Movies",While settling the affairs of his murdered mot...
8546,s8547,Movie,The Unknown Girl,"Jean-Pierre Dardenne, Luc Dardenne","Adèle Haenel, Olivier Bonnaud, Jérémie Renier,...","Belgium, France",2017-12-12,2016,TV-MA,106 min,"Dramas, International Movies",A guilt-ridden doctor in a Belgian town tries ...
2276,s2277,Movie,Inkaar,Sudhir Mishra,"Arjun Rampal, Chitrangada Singh, Deepti Naval,...",India,2020-07-05,2013,TV-MA,125 min,"Dramas, International Movies, Romantic Movies",An ad agency CEO is put under investigation wh...
5860,s5861,Movie,My Beautiful Broken Brain,"Sophie Robinson, Lotje Sodderland","Sophie Robinson, Lotje Sodderland",United Kingdom,2016-03-18,2016,TV-14,84 min,"Documentaries, International Movies","After suffering a stroke at age 34, a woman do..."
8300,s8301,Movie,The First Temptation of Christ,Rodrigo Van Der Put,"Gregorio Duvivier, Fábio Porchat, Antonio Tabe...",Brazil,2019-12-03,2019,TV-MA,46 min,"Comedies, International Movies","Jesus, who's hitting the big 3-0, brings a sur..."